// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcxwpmhsoekqcaczglmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeHdwbWhzb2VrcWNhY3pnbG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjQwMTgsImV4cCI6MjA2Mzk0MDAxOH0.TX2yHhQnDox0qrCFHLv4JT7mrhTBneraGXjG0Ztgkf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);